[workspace]
resolver = "2"
members = [
  "tdc",
  "todochad",
]

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
strip = true
debug = false
opt-level = "z"
lto = "thin" 
codegen-units = 1
panic = "abort"

