[package]
name = "todochad"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8"
serde = { version = "1", features = ["derive"] }
slab = { version = "0.4.9", features = ["serde"] }
thiserror = "2"
